# Sync watched status between media servers locally

services:
  jellyplex-watched:
    image: Turiko313/jellyplex-watched:latest
    container_name: jellyplex-watched
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    env_file: "./.env"
